Create APIFamilyproposal_Identity&Consent.md
camaraproject/WorkingGroups pull request #116
Opened 2023-01-09 13:48 UTC by shilpa-padgaonkar

Added draft page to propose identity and consent subproject

2023-01-09 15:38 UTC, shilpa-padgaonkar commented on APIBacklog/documentation/SupportingDocuments/API proposals/APIFamilyproposal_Identity&Consent.md
> +| Validated in lab/productive environments? | YES <br>|
I guess this validation is also NO? Is this validated already?

2023-01-09 15:41 UTC, jordonezlucena requested changes

2023-01-09 15:44 UTC, jordonezlucena approved these changes

2023-01-10 10:46 UTC, jordonezlucena approved these changes

2023-01-18 00:03 UTC, merged